### ISSUE TITLE
Chooser or swticher?

### ISSUE THREAD

**Issue by yochananmarqos** [ahoneybun/keyboard-color-switcher#5]
The repo is named `keyboard-color-chooser`, but the main Python script is `keyboard-color-switcher`.  🤔️ The folder and the script matched in the [System76-Utilities](https://github.com/roaldi/System76-Utilities/tree/main/keyboard-color-switcher) repo.

**Comment by ahoneybun** [comment]
Yea it's kinda all of the place isn't it lol. I think it's mainly switcher.

**Comment by yochananmarqos** [comment]
Well, once you figure that out, I'll add it to the AUR. :wink:

**Comment by ahoneybun** [comment]
Keyboard Color Switcher it is then lol.
