### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container

### ISSUE THREAD

**Issue by yochananmarqos** [ahoneybun/keyboard-color-switcher#9]
I just tried it from the 1.0 tag:

```
Traceback (most recent call last):
  File "/opt/keyboard-color-switcher/keyboard-color-switcher.py", line 7, in <module>
    from gi.repository import Gtk, Gio
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
```

Serval WS
Manjaro GNOME
`gtk3` 3.24.24
`python` 3.9.1
`python-gobject` 3.38.0

**Comment by ahoneybun** [comment]
What did you run for this to happen? Is it from the build process for PKGBUILD or from running `sudo python3 keyboard-color-switcher.py` ? What is the hardware as well?

**Comment by JeffLabonte** [comment]
@ahoneybun it seems like it is unable to import `Gtk` because it doesn't have `Container`?

**Comment by ahoneybun** [comment]
It's just odd that I haven't seen it on my system (oryp4). I'll boot in to my Manjaro to test.

**Comment by yochananmarqos** [comment]
I'm  working on a PKGBUILD with a Polkit policy which worked earlier today. I also tried running `sudo python keyboard-color-switcher.py`. directly from the repo as well. This is on my Serval WS.

**Comment by ahoneybun** [comment]
I can't recreate it since my other system is a `galp3-b` which doesn't have the backlights.

**Comment by ahoneybun** [comment]
I wonder if it is because `python` was used instead of `python3`?

**Comment by JeffLabonte** [comment]
Arch Linux tends to use bleeding edge software and disregard older versions. There could be a breaking change in the version used by @yochananmarqos. It will need more investigation. 

You are using the latest version of Manjaro with Gnome @yochananmarqos? Any special repository or using unstable repositories from Manjaro?

**Comment by yochananmarqos** [comment]
@ahoneybun On Arch, `python` is the current version, 3.9. 

On Ubuntu, it's the other way around: `python` is Python 2. 

I'm using the Manjaro unstable branch which syncs with Arch stable multiple times a day.

**Comment by ahoneybun** [comment]
@JeffLabonte can you help me disable the laptop_model check so I can launch the application?

@yochananmarqos can you share your pacman.conf file for the unstable branch?

**Comment by yochananmarqos** [comment]
There was just a stable update today, you'll have the same software versions just about.

See here for switching branches:
 https://wiki.manjaro.org/index.php/Switching_Branches

**Comment by JeffLabonte** [comment]
@ahoneybun in the file `keyboard_backlight.py` in folder `kcc_cli`, you can change `self.laptop_model` at line 25 for string.

You can set oryp4 if you have 3 backlight path and oryp6 if you have one. Also, you can comment out line 23 in this case since it won't be used.

**Comment by ahoneybun** [comment]
@yochananmarqos I'm trying to set up Manjaro on my oryp4 but I don't have the /sys/class/leds path and I can't use the key combos.

**Comment by yochananmarqos** [comment]
@ahoneybun Install `system76-oled` from the AUR.

**Comment by ahoneybun** [comment]
It looks like it works now! I'll test the AUR package now.

**Comment by ahoneybun** [comment]
Looks like it built for me but when I tried to run it I get this:

/opt/keyboard-color-switcher/keyboard-color-switcher.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio
Traceback (most recent call last):
  File "/opt/keyboard-color-switcher/keyboard-color-switcher.py", line 9, in <module>
    from kcc_cli.keyboard_backlight import KeyboardBacklight
ModuleNotFoundError: No module named 'kcc_cli'

**Comment by yochananmarqos** [comment]
I [updated](https://github.com/yochananmarqos/pkgbuilds/commit/db4adc5467965963fe4f80109c55095c6a517183#diff-f35a843302b73a6e77eba7aad8afb00936f3955f14ce6a22e646e7a5b7f44d34) my PKGBUILD to install to `site-packages instead:

```
/usr/lib/python3.9/site-packages/keyboard-color-switcher
├── kcc
└── kcc_cli
└── keyboard-color-switcher.py
```

Now I get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 7, in <module>
    from gi.repository import Gtk, Gio
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
```

**Comment by ahoneybun** [comment]
I did a git pull then built the package again and it works for me.

**Comment by yochananmarqos** [comment]
Hmm... I had `gtk4` installed for testing and just removed it.

```
/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 110, in <module>
    win = MainWindow()
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 27, in __init__
    self.keyboard_backlight = KeyboardBacklight()
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/kcc_cli/keyboard_backlight.py", line 30, in __init__
    f"{laptop_model} is not supported by this script"
NameError: name 'laptop_model' is not defined
```

**Comment by ahoneybun** [comment]
It looks like it isn't detecting this model as supported. What version of the Serval is this? I think only the serw12 is in the program right now.

**Comment by yochananmarqos** [comment]
Yes, it's the serw12.

```
❯ sudo dmidecode -s  system-product-name
Serval WS
```

**Comment by ahoneybun** [comment]
I'm not sure how @JeffLabonte set it to detect models and if it is using a database to do that. It has to somewhere.

**Comment by ahoneybun** [comment]
Oh I see it!

**Comment by yochananmarqos** [comment]
serw12 is [missing](https://github.com/ahoneybun/keyboard-color-switcher/blob/master/kcc_cli/keyboard_backlight.py#L19). I added `'serw12': FOUR_BACKLIGHT_PATH,` and now...

```
/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 110, in <module>
    win = MainWindow()
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 29, in __init__
    Gtk.Window.__init__(self)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 515, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case
```

**Comment by ahoneybun** [comment]
Can you share this output? 

cat /sys/class/leds/

**Comment by yochananmarqos** [comment]
```
❯ ls /sys/class/leds
input30::capslock  input30::numlock	input4::numlock     system76::airplane
input30::compose   input30::scrolllock	input4::scrolllock  system76::kbd_backlight
input30::kana	   input4::capslock	phy0-led
```

**Comment by yochananmarqos** [comment]
I added the following [here](https://github.com/ahoneybun/keyboard-color-switcher/blob/master/keyboard-color-switcher.py#L6):
```
import gi
gi.require_version('Gtk', '3.0') # <--
from gi.repository import Gtk, Gio
```

This works now, however [running GUI applications as root](https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root) isn't really the greatest idea in the world.
```
sudo /usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py
```

Well, so much for the Polkit policy. For some reason that was causing an issue:

```
❯ pkexec /usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py

Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 111, in <module>
    win = MainWindow()
  File "/usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 30, in __init__
    Gtk.Window.__init__(self)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 515, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.


```

**Comment by ahoneybun** [comment]
It looks better with that prompt though I don't know if that works in Wayland or not though that's another task to deal with later I think.

**Comment by yochananmarqos** [comment]
With `zensu` (provides `gksu`) you can use `spacefm`, `kdialog`, `yad` or `zenity` for the prompt. It will look for them in that order. I have `yad` installed as a dependency for something else, so it's using that for me.

With `pkexec`, it uses the system dialog just like when `systemctl enable some.service` is used, for instance.

**Comment by ahoneybun** [comment]
@JeffLabonte so it sounds like `color_extra` is for the backlight on the front of some systems like the `serw11` and `serw12`.

**Comment by ahoneybun** [comment]
Using zensu certainly works for what we need!

**Comment by ahoneybun** [comment]
I don't think `system76-oled` is really needed tbh.

**Comment by yochananmarqos** [comment]
>  it sounds like color_extra is for the backlight on the front of some systems like the serw11 and serw12.

You mean on the lid? That color doesn't change. `color_left` is the whole keyboard, the others don't do anything.

> Using zensu certainly works for what we need!

It's not ideal, but it'll work for now.

> I don't think system76-oled is really needed tbh.

But you said... 
> I don't have the /sys/class/leds path and I can't use the key combos.

What did you install that exposed the path, then? You'll need `system76-dkms` for the hotkeys.

**Comment by ahoneybun** [comment]
I didn't have the system76-dkms package when I installed the oled package. Then I installed dkms then rebooted and the  path was there.

**Comment by ahoneybun** [comment]
I'm sorry for the extra messages I believe we are getting off course to fix your issue. I'm a bit worried about these messages as well:

Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

Are you using Xorg or Wayland?

**Comment by yochananmarqos** [comment]
That was from `pkexec`, don't worry about that.

**Comment by yochananmarqos** [comment]
Merge #11 and we're golden!

**Comment by ahoneybun** [comment]
Is the main issue fixed as well?

**Comment by yochananmarqos** [comment]
See: #12

**Comment by ahoneybun** [comment]
Alright so I recreated it on my system though I can run the application just fine like this:

`keyboard-color-switcher`

**Comment by yochananmarqos** [comment]
Right, so can I. Effectively, the issue is solved. 

Part of the issue was not declaring the GTK version. Since I had Gtk 4 installed, it threw it off.

The other part of the issue was using the Polkit policy which I've put on hold for now. I'll figure that out later.

**Comment by ahoneybun** [comment]
I'll keep looking into it when I can unless @JeffLabonte has any ideas. There don't seem to be a ton of reports of the behavior.

**Comment by yochananmarqos** [comment]
Well, no. Not many people would have Gtk 4 installed yet, for one. Either way, that's solved now.

**Comment by ahoneybun** [comment]
I don't have GTK 4 installed as far as I know of.

**Comment by yochananmarqos** [comment]
No, you wouldn't as nothing stable requires it yet. I was testing new software.

**Comment by ahoneybun** [comment]
Well the oddness is that I can recreate the issue without GTK 4.

**Comment by yochananmarqos** [comment]
You can? 

After today's unstable branch updates including `gtk3` to 3.24.25, I now cannot reproduce the issue with the Polikit policy.  My PKGBUILD is updated to install it again.

**Comment by ahoneybun** [comment]
I haven't run it today with the recent changes.

**Comment by ahoneybun** [comment]
It sounds like this issue has been fixed correct? I can run it like this with no issue:

sudo /usr/lib/python3.9/site-packages/keyboard-color-switcher/keyboard-color-switcher.py

**Comment by yochananmarqos** [comment]
If you installed it via my PKGBUILD, don't run it like that. The whole idea was to [use `pkexec`](https://github.com/yochananmarqos/pkgbuilds/blob/master/keyboard-color-switcher-git/keyboard-color-switcher.sh#L5). Just run `keyboard-color-switcher`.

**Comment by JeffLabonte** [comment]
@yochananmarqos @ahoneybun I will consider the issue fixed and close this issue! 😄
